# .readthedocs.yaml
# Read the Docs configuration file for torchdiff documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and tools needed for building
build:
  os: ubuntu-24.04
  tools:
    python: "3.12" 
    
format:
   - pdf

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Declare Python requirements to build the documentation
python:
  install:
    - requirements: docs/requirements.txt
